name: First CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: |
          echo "🚀 CI запущен!"
          echo "Ветка: ${{ github.ref }}"
          echo "Коммит: ${{ github.sha }}"
          pwd
          ls -la

      - name: Check Docker
        run: |
          docker --version
          docker info